theme: jekyll-theme-slate
title: GitHub Structured
author: Alvaro Faundez
email: alvaro@faundez.net
description: >
  All my GitHub projects in one place.
twitter_username: afaundez
github_username:  afaundez
